version: '3.8'

services:
  db: 
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      exam-net:
        ipv4_address: 172.20.2.2

  backend:
    build:
      context: ./examReady/
      dockerfile: ./examReady/Dockerfile
    container_name: backend
    # ports:
    #   - "8080:8080"
    depends_on:
      - db  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD} 
    networks:
      exam-net:
        ipv4_address: 172.20.2.3
        
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    working_dir: /next
    ports:
    - "3000:3000"
    environment:
      - GOOGLE_CLIENT_ID= ${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET= ${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET= ${NEXTAUTH_SECRET}
      - NEXTAUTH_URL= ${NEXTAUTH_URL}
      - NEXT_PUBLIC_SERVER= ${NEXT_PUBLIC_SERVER}
      - NEXT_PUBLIC_SERVER_PORT= ${NEXT_PUBLIC_SERVER_PORT}
    networks:
      exam-net:
        ipv4_address: 172.20.2.4
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      exam-net:
        ipv4_address: 172.20.2.5

volumes:
  mysql_data:

networks:
  exam-net:
    driver: bridge
    name: exam-net
    ipam: 
      driver: default
      config: 
        - subnet: 172.20.2.0/28

        